### ISSUE TITLE
Fade-out duration is not configurable

### ISSUE THREAD

**Issue by porst17** [IMAGINARY/content-slider-announcer#2]
The fade-in duration is configurable, but not the fade-out duration. It is hard-coded to 2s as it seems.

I implemented a simple tool for stepping through all announcements in the content-slider. This is very handy for doing final checks of all texts. But the user has to click on the announcement to move to the next one (which is sane behavior). This always involves a 2s delay before the next announcement can appear, which I would like to reduce to 0s.

**Comment by elondaits** [comment]
Implemented in 52d31e7652a35bbcf509ee1a03a0a7f3169b0035 and released on v1.2.0

**Comment by elondaits** [comment]
Implemented in 7f95a6f4152d4cbba2f637e5979fa65f9577a33b and released as v1.2.1
